"""Dump the client's (WGR) full Postgres schema to a markdown reference.

Read-only. Uses app.services.wgr_client (which forces READ ONLY sessions).
Writes docs/client-supabase-schema.md — the authoritative map we build the
sync mappings from. Re-run any time to refresh.

Usage (from backend/):
    .venv/bin/python -m scripts.dump_wgr_schema
"""

from __future__ import annotations

import pathlib

from app.services import wgr_client

OUT = pathlib.Path(__file__).resolve().parents[2] / "docs" / "client-supabase-schema.md"


def main() -> None:
    tables = wgr_client.list_tables()
    fks = wgr_client.foreign_keys()
    fk_by_table: dict[str, list[dict]] = {}
    for fk in fks:
        fk_by_table.setdefault(fk["from_table"], []).append(fk)

    counts = {t: wgr_client.count(t) for t in tables}
    non_empty = [t for t in tables if counts[t] > 0]
    empty = [t for t in tables if counts[t] == 0]

    lines: list[str] = []
    lines.append("# Client (WGR) Supabase — full Postgres schema")
    lines.append("")
    lines.append(
        "> Auto-generated by `scripts/dump_wgr_schema.py` via the read-only "
        "`WGR_DATABASE_URL` connection. Re-run to refresh. Authoritative over the "
        "anon-probed inventory in `client-supabase-connection.md`."
    )
    lines.append("")
    lines.append(
        f"**{len(tables)} tables total — {len(non_empty)} non-empty, "
        f"{len(empty)} empty.** Scope decision (2026-06-17): ingest everything non-empty."
    )
    lines.append("")

    # FK graph first — it's the join map for the mappings.
    lines.append("## Foreign-key graph (declared constraints)")
    lines.append("")
    if fks:
        lines.append("| From | → | To |")
        lines.append("|------|---|----|")
        for fk in fks:
            lines.append(
                f"| `{fk['from_table']}.{fk['from_column']}` | → | "
                f"`{fk['to_table']}.{fk['to_column']}` |"
            )
    else:
        lines.append("_No declared FK constraints found._")
    lines.append("")

    lines.append("## Non-empty tables")
    lines.append("")
    for t in non_empty:
        _emit_table(lines, t, counts[t], fk_by_table.get(t, []))

    lines.append("## Empty tables (schema only)")
    lines.append("")
    for t in empty:
        _emit_table(lines, t, 0, fk_by_table.get(t, []))

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} — {len(tables)} tables ({len(non_empty)} non-empty).")


def _emit_table(lines: list[str], table: str, n: int, fks: list[dict]) -> None:
    pks = set(wgr_client.primary_keys(table))
    cols = wgr_client.columns(table)
    lines.append(f"### `{table}` — {n:,} rows, {len(cols)} columns")
    lines.append("")
    lines.append("| Column | Type | Null | PK | Default |")
    lines.append("|--------|------|------|----|---------|")
    for c in cols:
        pk = "🔑" if c["column_name"] in pks else ""
        default = (c["column_default"] or "").split("::")[0][:30]
        lines.append(
            f"| `{c['column_name']}` | {c['data_type']} | "
            f"{c['is_nullable']} | {pk} | {default} |"
        )
    if fks:
        rels = ", ".join(f"`{f['from_column']}`→`{f['to_table']}.{f['to_column']}`" for f in fks)
        lines.append("")
        lines.append(f"FKs: {rels}")
    lines.append("")


if __name__ == "__main__":
    main()
