"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Header } from "@/components/layout/header";
import { apiClient, ApiError } from "@/lib/api-client";
import { useAuth } from "@/hooks/use-auth";
import { showError, showWarning } from "@/lib/toast";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { Breadcrumbs, resolveOrigin } from "@/components/ui/breadcrumbs";
import { Button } from "@/components/ui/button";
import { SparkleIcon } from "@/components/ui/sparkle-icon";

// ─── Types ────────────────────────────────────────────────────────────────────

interface CallDetail {
  call_id: string;
  date: string | null;
  call_type: string | null;
  call_result: string | null;
  call_owner: string | null;
  transcript_quality: string | null;
  processed_date: string | null;
  transcript: string | null;
  summary: string | null;
  created_at: string | null;
  source: string | null;
}

// ─── Provenance ─────────────────────────────────────────────────────────────────
//
// `source === "wgr"` means the record (and its insights/content ideas) was
// mirrored read-only from the client's WGR database — generated by their
// pipeline, not CI's analyzer. Anything else is CI-native (uploaded + analyzed
// here, so Re-analyze regenerates it).

function ProvenanceBadge({ source }: { source: string | null }) {
  const isWgr = source === "wgr";
  return (
    <span
      className={`text-[11px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded border ${
        isWgr
          ? "bg-violet-50 text-violet-700 border-violet-200"
          : "bg-sky-50 text-sky-700 border-sky-200"
      }`}
      title={
        isWgr
          ? "Synced read-only from the client (WGR) database — analyzed by their pipeline"
          : "Uploaded and analyzed in Central Intelligence"
      }
    >
      {isWgr ? "WGR-synced" : "CI-analyzed"}
    </span>
  );
}

interface InsightBrief {
  insight_id: string;
  insight_type: string | null;
  signal_family: string | null;
  signal: string | null;
  raw_quote: string | null;
  // ── Deep analysis (shown in the expandable section) ──
  speaker_name?: string | null;
  signal_strength?: string | null;
  pain_layer?: string | null;
  what_they_say?: string | null;
  the_real_problem?: string | null;
  emotional_driver?: string | null;
  core_fear_revealed?: string | null;
  false_belief_revealed?: string | null;
  structural_obstacle?: string | null;
  identity_signal?: string | null;
  buying_trigger?: string | null;
  objection_created?: string | null;
  marketing_translation?: string | null;
  hook_angle_example?: string | null;
  best_use_case?: string | null;
  quote_confidence?: string | null;
  frequency_score?: number | null;
}

// Field groupings for the expandable insight detail. Each entry is
// [object key, human label]. Rendered only when the value is non-empty.
const PSYCHOLOGY_FIELDS: Array<[keyof InsightBrief, string]> = [
  ["what_they_say", "What they say"],
  ["the_real_problem", "The real problem"],
  ["emotional_driver", "Emotional driver"],
  ["core_fear_revealed", "Core fear revealed"],
  ["false_belief_revealed", "False belief revealed"],
  ["structural_obstacle", "Structural obstacle"],
  ["identity_signal", "Identity signal"],
  ["pain_layer", "Pain layer"],
];

const MARKETING_FIELDS: Array<[keyof InsightBrief, string]> = [
  ["marketing_translation", "Marketing translation"],
  ["hook_angle_example", "Hook angle example"],
  ["buying_trigger", "Buying trigger"],
  ["objection_created", "Objection created"],
  ["best_use_case", "Best use case"],
];

interface ContentIdeaBrief {
  content_id: string;
  content_format: string | null;
  status: string | null;
  priority_level: string | null;
  idea_score: number | null;
  // ── Full brief (shown on the call detail card) ──
  market_audience?: string | null;
  content_angle?: string | null;
  trigger_insight?: string | null;
  raw_quote?: string | null;
  content_premise?: string | null;
  hook_opening_line?: string | null;
  teaching_point?: string | null;
  cta_idea?: string | null;
  best_platform?: string | null;
  repurpose_opportunities?: string | null;
}

interface CallDetailResponse {
  call: CallDetail;
  insights: InsightBrief[];
  content_ideas: ContentIdeaBrief[];
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

// Humanize a stored taxonomy value for display only. Some insights were stored
// with the analyzer's raw vocabulary (snake_case / lowercase, e.g.
// "buying_signal", "value_clarity") while most use WGR's Title Case
// ("Buying Signal", "Skills & Competency"). This normalizes the raw ones at
// render time so both read the same. The underlying value is never mutated —
// edits still save the raw string.
function humanizeLabel(value: string | null): string | null {
  if (value === null) return null;
  const trimmed = value.trim();
  if (trimmed === "") return value;
  // Leave already-human values alone: anything with a space or an internal
  // uppercase letter is treated as already formatted (e.g. "Skills & Competency").
  if (/\s/.test(trimmed) || /[A-Z]/.test(trimmed.slice(1))) return value;
  return trimmed
    .split(/[_-]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function formatDate(iso: string | null): string {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
    });
  } catch {
    return iso;
  }
}

async function downloadTranscript(callId: string): Promise<void> {
  let blob: Blob;
  try {
    blob = await apiClient.getBlob(`/ci/calls/${callId}/transcript.txt`, { silent: true });
  } catch (err) {
    if (err instanceof ApiError && err.status === 404) {
      showWarning("No transcript on file for this call.");
    } else {
      const status = err instanceof ApiError ? err.status : "unknown";
      showError(`Download failed (${status})`);
    }
    return;
  }
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${callId}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Inline-edit primitives ───────────────────────────────────────────────────
//
// Two flavors live on this page:
//  - InlineTextEdit: single-line input for short metadata (owner, type, result)
//  - InlineTextareaEdit: multi-line textarea for summary + insight fields
//
// Both use the same pattern: render `displayValue` until clicked, then swap to
// an input with Save / Cancel. Saving calls `onSave(newValue)` and the parent
// decides what to do with it (PATCH the API, update state, etc.).

interface InlineTextEditProps {
  value: string | null;
  placeholder?: string;
  emptyLabel?: string;
  className?: string;
  inputClassName?: string;
  // Display-only transform (e.g. humanizeLabel). The edit input still shows the
  // raw value and saves it unchanged — this only affects the read-mode label.
  displayTransform?: (v: string | null) => string | null;
  onSave: (next: string | null) => Promise<void> | void;
}

function InlineTextEdit({
  value,
  placeholder = "",
  emptyLabel = "—",
  className = "",
  inputClassName = "",
  displayTransform,
  onSave,
}: InlineTextEditProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [draft, setDraft] = useState(value ?? "");
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    if (!isEditing) setDraft(value ?? "");
  }, [value, isEditing]);

  if (!isEditing) {
    const shown = displayTransform ? displayTransform(value) : value;
    const display = shown && shown.trim() !== "" ? shown : emptyLabel;
    const isEmpty = !value || value.trim() === "";
    return (
      <button
        type="button"
        onClick={() => setIsEditing(true)}
        className={`text-left hover:bg-amber-50/60 rounded px-1 -mx-1 transition-colors ${
          isEmpty ? "text-gray-400 italic" : ""
        } ${className}`}
        title="Click to edit"
      >
        {display}
      </button>
    );
  }

  async function commit() {
    setIsSaving(true);
    try {
      const next = draft.trim() === "" ? null : draft;
      await onSave(next);
      setIsEditing(false);
    } catch (err) {
      showError(err instanceof Error ? err.message : "Save failed.");
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <span className="inline-flex items-center gap-1.5">
      <input
        type="text"
        value={draft}
        placeholder={placeholder}
        autoFocus
        disabled={isSaving}
        onChange={(e) => setDraft(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") void commit();
          if (e.key === "Escape") setIsEditing(false);
        }}
        className={`border border-accent-300 rounded px-1.5 py-0.5 focus:outline-none focus:ring-2 focus:ring-accent-300/50 ${inputClassName}`}
      />
      <button
        type="button"
        onClick={() => void commit()}
        disabled={isSaving}
        className="text-[12px] font-medium text-accent-600 hover:text-accent-700"
      >
        {isSaving ? "…" : "Save"}
      </button>
      <button
        type="button"
        onClick={() => setIsEditing(false)}
        disabled={isSaving}
        className="text-[12px] text-gray-400 hover:text-gray-600"
      >
        Cancel
      </button>
    </span>
  );
}

interface InlineSelectEditProps {
  value: string | null;
  // Fixed choice list (e.g. the rep roster). The current value is offered as an
  // extra option when it isn't in the list, so legacy/former-rep owners remain
  // selectable instead of being silently clobbered.
  options: string[];
  emptyLabel?: string;
  className?: string;
  onSave: (next: string | null) => Promise<void> | void;
}

function InlineSelectEdit({
  value,
  options,
  emptyLabel = "—",
  className = "",
  onSave,
}: InlineSelectEditProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [draft, setDraft] = useState(value ?? "");
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    if (!isEditing) setDraft(value ?? "");
  }, [value, isEditing]);

  if (!isEditing) {
    const isEmpty = !value || value.trim() === "";
    return (
      <button
        type="button"
        onClick={() => setIsEditing(true)}
        className={`text-left hover:bg-amber-50/60 rounded px-1 -mx-1 transition-colors ${
          isEmpty ? "text-gray-400 italic" : ""
        } ${className}`}
        title="Click to edit"
      >
        {isEmpty ? emptyLabel : value}
      </button>
    );
  }

  const currentNotInOptions =
    value !== null && value.trim() !== "" && !options.includes(value);

  async function commit() {
    setIsSaving(true);
    try {
      await onSave(draft.trim() === "" ? null : draft);
      setIsEditing(false);
    } catch (err) {
      showError(err instanceof Error ? err.message : "Save failed.");
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <span className="inline-flex items-center gap-1.5">
      <select
        value={draft}
        autoFocus
        disabled={isSaving}
        onChange={(e) => setDraft(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") void commit();
          if (e.key === "Escape") setIsEditing(false);
        }}
        className="border border-accent-300 rounded px-1.5 py-0.5 text-[13px] bg-white focus:outline-none focus:ring-2 focus:ring-accent-300/50"
      >
        <option value="">{emptyLabel}</option>
        {currentNotInOptions && <option value={value as string}>{value} (former)</option>}
        {options.map((o) => (
          <option key={o} value={o}>
            {o}
          </option>
        ))}
      </select>
      <button
        type="button"
        onClick={() => void commit()}
        disabled={isSaving}
        className="text-[12px] font-medium text-accent-600 hover:text-accent-700"
      >
        {isSaving ? "…" : "Save"}
      </button>
      <button
        type="button"
        onClick={() => setIsEditing(false)}
        disabled={isSaving}
        className="text-[12px] text-gray-400 hover:text-gray-600"
      >
        Cancel
      </button>
    </span>
  );
}

interface InlineTextareaEditProps {
  value: string | null;
  rows?: number;
  emptyMessage: React.ReactNode;
  className?: string;
  onSave: (next: string | null) => Promise<void> | void;
}

function InlineTextareaEdit({
  value,
  rows = 5,
  emptyMessage,
  className = "",
  onSave,
}: InlineTextareaEditProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [draft, setDraft] = useState(value ?? "");
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    if (!isEditing) setDraft(value ?? "");
  }, [value, isEditing]);

  if (!isEditing) {
    return (
      <button
        type="button"
        onClick={() => setIsEditing(true)}
        className="block w-full text-left hover:bg-amber-50/60 rounded p-1 -m-1 transition-colors"
        title="Click to edit"
      >
        {value && value.trim() !== "" ? (
          <p className={`whitespace-pre-wrap leading-relaxed ${className}`}>{value}</p>
        ) : (
          emptyMessage
        )}
      </button>
    );
  }

  async function commit() {
    setIsSaving(true);
    try {
      const next = draft.trim() === "" ? null : draft;
      await onSave(next);
      setIsEditing(false);
    } catch (err) {
      showError(err instanceof Error ? err.message : "Save failed.");
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <div className="space-y-2">
      <textarea
        value={draft}
        rows={rows}
        autoFocus
        disabled={isSaving}
        onChange={(e) => setDraft(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Escape") setIsEditing(false);
          // Cmd+Enter / Ctrl+Enter to save (Enter alone is a newline in a textarea)
          if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) void commit();
        }}
        className={`w-full border border-accent-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-accent-300/50 ${className}`}
      />
      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={() => void commit()}
          disabled={isSaving}
          className="text-[13px] font-medium px-3 py-1 rounded-lg bg-accent-500 hover:bg-accent-600 disabled:bg-accent-200 disabled:cursor-not-allowed text-white"
        >
          {isSaving ? "Saving…" : "Save"}
        </button>
        <button
          type="button"
          onClick={() => setIsEditing(false)}
          disabled={isSaving}
          className="text-[13px] text-gray-500 hover:text-gray-700"
        >
          Cancel
        </button>
        <span className="text-[11px] text-gray-400 ml-auto">⌘+Enter saves · Esc cancels</span>
      </div>
    </div>
  );
}

// ─── Insight row (summary + expandable deep analysis) ───────────────────────────

interface InsightRowProps {
  insight: InsightBrief;
  onSaveField: (field: keyof InsightBrief, value: string | null) => Promise<void> | void;
  onDelete: () => void;
}

/** One field of the deep-analysis block — label + value, hidden when empty. */
function DetailField({ label, value }: { label: string; value: string | null | undefined }) {
  if (!value || value.trim() === "") return null;
  return (
    <div>
      <dt className="text-[11px] font-semibold uppercase tracking-wider text-gray-400">{label}</dt>
      <dd className="text-[13px] text-gray-700 mt-0.5 whitespace-pre-wrap leading-relaxed">{value}</dd>
    </div>
  );
}

function InsightRow({ insight: ins, onSaveField, onDelete }: InsightRowProps) {
  const [expanded, setExpanded] = useState(false);

  // Which deep fields actually have content — drives whether the toggle shows.
  const psychFields = PSYCHOLOGY_FIELDS.filter(([k]) => {
    const v = ins[k];
    return typeof v === "string" && v.trim() !== "";
  });
  const mktFields = MARKETING_FIELDS.filter(([k]) => {
    const v = ins[k];
    return typeof v === "string" && v.trim() !== "";
  });
  const hasDetail = psychFields.length > 0 || mktFields.length > 0;

  return (
    <div className="px-5 py-3 group">
      <div className="flex items-center gap-2 flex-wrap">
        <span className="text-[11px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded bg-accent-50 text-accent-700 border border-accent-200">
          <InlineTextEdit
            value={ins.insight_type}
            placeholder="type"
            emptyLabel="type"
            inputClassName="text-[11px] uppercase"
            displayTransform={humanizeLabel}
            onSave={(v) => onSaveField("insight_type", v)}
          />
        </span>
        <span className="text-[11px] text-gray-500">
          <InlineTextEdit
            value={ins.signal_family}
            placeholder="signal_family"
            emptyLabel="family"
            inputClassName="text-[11px]"
            displayTransform={humanizeLabel}
            onSave={(v) => onSaveField("signal_family", v)}
          />
        </span>
        {ins.signal_strength && (
          <span className="text-[10px] font-medium px-1.5 py-0.5 rounded bg-gray-100 text-gray-600 border border-gray-200">
            {humanizeLabel(ins.signal_strength)}
          </span>
        )}
        <button
          type="button"
          onClick={onDelete}
          className="ml-auto text-[11px] text-red-500 hover:text-red-700 opacity-0 group-hover:opacity-100 transition-opacity"
          title="Delete this insight"
        >
          Delete
        </button>
      </div>
      <div className="text-[15px] font-medium text-gray-900 mt-1">
        <InlineTextEdit
          value={ins.signal}
          placeholder="Signal label"
          emptyLabel="(no signal)"
          inputClassName="text-[15px] font-medium w-full min-w-[400px]"
          className="block"
          onSave={(v) => onSaveField("signal", v)}
        />
      </div>
      <div className="text-[13px] text-gray-600 italic mt-1">
        <InlineTextareaEdit
          value={ins.raw_quote}
          rows={2}
          className="text-[13px] not-italic"
          emptyMessage={<span className="text-gray-400">(no quote)</span>}
          onSave={(v) => onSaveField("raw_quote", v)}
        />
      </div>

      {/* Deep analysis — collapsed by default, keeps the list scannable. */}
      {hasDetail && (
        <div className="mt-2">
          <button
            type="button"
            onClick={() => setExpanded((e) => !e)}
            className="text-[12px] font-medium text-accent-600 hover:text-accent-700 inline-flex items-center gap-1"
          >
            <span
              className={`inline-block transition-transform ${expanded ? "rotate-90" : ""}`}
              aria-hidden="true"
            >
              ▶
            </span>
            {expanded ? "Hide analysis" : "Show analysis"}
          </button>

          {expanded && (
            <div className="mt-3 grid sm:grid-cols-2 gap-x-6 gap-y-4 rounded-lg bg-gray-50 border border-gray-100 p-4">
              {psychFields.length > 0 && (
                <div className="space-y-3">
                  <p className="text-[11px] font-bold uppercase tracking-wider text-accent-500">
                    Psychology
                  </p>
                  <dl className="space-y-3">
                    {psychFields.map(([k, label]) => (
                      <DetailField
                        key={k}
                        label={label}
                        // pain_layer is a taxonomy value (surface/tactical/…);
                        // the rest are prose, shown as-is.
                        value={
                          k === "pain_layer"
                            ? humanizeLabel(ins[k] as string | null)
                            : (ins[k] as string | null)
                        }
                      />
                    ))}
                  </dl>
                </div>
              )}
              {mktFields.length > 0 && (
                <div className="space-y-3">
                  <p className="text-[11px] font-bold uppercase tracking-wider text-emerald-500">
                    Marketing
                  </p>
                  <dl className="space-y-3">
                    {mktFields.map(([k, label]) => (
                      <DetailField key={k} label={label} value={ins[k] as string | null} />
                    ))}
                  </dl>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Content idea card (full shootable brief) ───────────────────────────────────

function ContentIdeaCard({ idea }: { idea: ContentIdeaBrief }) {
  return (
    <div className="px-5 py-4 space-y-3">
      {/* Header: format · platform · priority · score */}
      <div className="flex items-center gap-2 flex-wrap">
        <span className="text-[11px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200">
          {idea.content_format ?? "Idea"}
        </span>
        {idea.best_platform && (
          <span className="text-[11px] text-gray-500 capitalize">{idea.best_platform}</span>
        )}
        {idea.content_angle && (
          <span className="text-[10px] font-medium px-1.5 py-0.5 rounded bg-gray-100 text-gray-600 border border-gray-200 capitalize">
            {idea.content_angle}
          </span>
        )}
        <span className="ml-auto flex items-center gap-2">
          {idea.priority_level && (
            <span className="text-[11px] font-medium text-gray-600">{idea.priority_level} priority</span>
          )}
          {idea.idea_score != null && (
            <span className="text-[11px] font-semibold text-emerald-700">{idea.idea_score}/10</span>
          )}
          {idea.status && <span className="text-[11px] text-gray-400">{idea.status}</span>}
        </span>
      </div>

      {/* Hook — the literal opening line, given visual weight */}
      {idea.hook_opening_line && idea.hook_opening_line.trim() !== "" && (
        <div className="rounded-lg bg-amber-50 border border-amber-200 px-3 py-2">
          <p className="text-[10px] font-semibold uppercase tracking-wider text-amber-600">Hook</p>
          <p className="text-[15px] font-medium text-gray-900 mt-0.5 leading-snug">
            “{idea.hook_opening_line}”
          </p>
        </div>
      )}

      {/* The brief */}
      <dl className="grid sm:grid-cols-2 gap-x-6 gap-y-3">
        <DetailField label="Premise" value={idea.content_premise} />
        <DetailField label="Teaching point" value={idea.teaching_point} />
        <DetailField label="Call to action" value={idea.cta_idea} />
        <DetailField label="Target audience" value={idea.market_audience} />
        <DetailField label="Repurpose as" value={idea.repurpose_opportunities} />
        <DetailField label="Trigger insight" value={idea.trigger_insight} />
      </dl>

      {/* The prospect quote that sparked the idea */}
      {idea.raw_quote && idea.raw_quote.trim() !== "" && (
        <p className="text-[13px] text-gray-500 italic border-l-2 border-gray-200 pl-3">
          “{idea.raw_quote}”
        </p>
      )}
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function CallDetailPage({ params }: { params: { call_id: string } }) {
  const { isLoading: authLoading } = useAuth();
  const callId = params.call_id;
  // Where the user came from (?from=…); defaults to Sales Calls for this page.
  const searchParams = useSearchParams();
  const origin = resolveOrigin(searchParams.get("from"), "sales-calls");

  const [detail, setDetail] = useState<CallDetailResponse | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Pending-delete state for the confirm dialog. When non-null, the dialog
  // is open and confirming deletes this insight id.
  const [pendingDeleteInsightId, setPendingDeleteInsightId] = useState<
    string | null
  >(null);
  const [isDeletingInsight, setIsDeletingInsight] = useState(false);
  const [isReanalyzing, setIsReanalyzing] = useState(false);

  // Rep roster for the Owner dropdown. Empty until loaded (or on failure), in
  // which case the Owner field falls back to the free-text inline edit.
  const [repNames, setRepNames] = useState<string[]>([]);
  useEffect(() => {
    if (authLoading) return;
    let cancelled = false;
    apiClient
      .get<{ reps: { rep_id: string; full_name: string; status: string }[] }>(
        "/reps",
        { silent: true },
      )
      .then((data) => {
        if (!cancelled) setRepNames(data.reps.map((r) => r.full_name));
      })
      .catch(() => {
        // Roster unavailable — Owner stays a free-text edit.
      });
    return () => {
      cancelled = true;
    };
  }, [authLoading]);

  // Track the processed_date at the moment Re-analyze starts so polls can
  // detect when fresh data has actually landed (vs serving stale rows).
  const reanalyzeBaselineRef = useRef<string | null>(null);

  const load = useCallback(
    async (opts: { showSpinner?: boolean; commit?: boolean } = {}) => {
      const showSpinner = opts.showSpinner ?? false;
      const commit = opts.commit ?? true;
      if (showSpinner) setIsLoading(true);
      setError(null);
      try {
        const data = await apiClient.get<CallDetailResponse>(`/ci/calls/${callId}`, {
          silent: true,
        });
        if (commit) setDetail(data);
        return data;
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load call.");
        return null;
      } finally {
        if (showSpinner) setIsLoading(false);
      }
    },
    [callId],
  );

  useEffect(() => {
    if (authLoading) return;
    void load({ showSpinner: true });
  }, [authLoading, load]);

  async function handleReanalyze() {
    reanalyzeBaselineRef.current = detail?.call.processed_date ?? null;
    setIsReanalyzing(true);
    try {
      await apiClient.post(`/ci/calls/${callId}/analyze`, {}, { silent: true });
      const maxAttempts = 30; // ~3 minutes at 6s
      const baseline = reanalyzeBaselineRef.current;
      for (let i = 0; i < maxAttempts; i += 1) {
        await new Promise((r) => setTimeout(r, 6000));
        const fresh = await load({ showSpinner: false, commit: false });
        if (fresh && fresh.call.processed_date && fresh.call.processed_date !== baseline) {
          setDetail(fresh);
          return;
        }
      }
      await load({ showSpinner: false, commit: true });
    } catch (err) {
      showError(err instanceof Error ? err.message : "Re-analyze failed.");
    } finally {
      setIsReanalyzing(false);
    }
  }

  // ─── PATCH helpers ──────────────────────────────────────────────────────────

  async function saveCallField(field: keyof CallDetail, value: string | null) {
    const updated = await apiClient.patch<CallDetail>(
      `/ci/calls/${callId}`,
      { [field]: value },
      { silent: true },
    );
    setDetail((d) => (d ? { ...d, call: updated } : d));
  }

  async function saveInsightField(
    insightId: string,
    field: keyof InsightBrief,
    value: string | null,
  ) {
    const updated = await apiClient.patch<InsightBrief>(
      `/ci/insights/${insightId}`,
      { [field]: value },
      { silent: true },
    );
    setDetail((d) =>
      d ? { ...d, insights: d.insights.map((i) => (i.insight_id === insightId ? updated : i)) } : d,
    );
  }

  function deleteInsight(insightId: string) {
    // Don't delete inline — open the ConfirmDialog and defer the actual
    // call to confirmDeleteInsight below. Using window.confirm here would
    // bypass the project's toast/dialog UX (CLAUDE.md rule).
    setPendingDeleteInsightId(insightId);
  }

  async function confirmDeleteInsight() {
    const insightId = pendingDeleteInsightId;
    if (!insightId) return;
    setIsDeletingInsight(true);
    try {
      await apiClient.delete(`/ci/insights/${insightId}`, { silent: true });
      setDetail((d) =>
        d ? { ...d, insights: d.insights.filter((i) => i.insight_id !== insightId) } : d,
      );
    } catch (err) {
      showError(err instanceof Error ? err.message : "Delete failed.");
    } finally {
      setIsDeletingInsight(false);
      setPendingDeleteInsightId(null);
    }
  }

  // ─── Render ─────────────────────────────────────────────────────────────────

  if (isLoading) {
    return (
      <>
        <Header title="Call detail" />
        <main className="flex-1 overflow-y-auto p-7">
          <p className="text-[15px] text-gray-400">Loading…</p>
        </main>
      </>
    );
  }

  if (error || detail === null) {
    return (
      <>
        <Header title="Call detail" />
        <main className="flex-1 overflow-y-auto p-7 space-y-4">
          <Breadcrumbs origin={origin} current="Call detail" />
          <p className="text-[15px] text-red-700">{error ?? "Call not found."}</p>
        </main>
      </>
    );
  }

  const { call, insights, content_ideas } = detail;

  // First-pass analyzer hasn't completed yet — no processed_date stamped.
  // Drives the "Analyzing…" placeholders below. Distinct from isReanalyzing
  // (manual re-run on an already-processed call).
  const isProcessing = !call.processed_date;

  return (
    <>
      <Header title="Call detail" />

      <main className="flex-1 overflow-y-auto p-7 space-y-6">
        {/* Breadcrumb — reflects where the user came from (?from=…) */}
        <Breadcrumbs origin={origin} current="Call detail" />

        {/* Header — editable metadata */}
        <div className="flex items-start justify-between gap-4">
          <div className="min-w-0">
            <h1 className="text-[22px] font-bold text-gray-900 truncate">
              <InlineTextEdit
                value={call.call_type}
                placeholder="Call type"
                emptyLabel="Call"
                inputClassName="text-[22px] font-bold"
                onSave={(v) => saveCallField("call_type", v)}
              />
              {" — "}
              {formatDate(call.created_at)}
            </h1>
            <p className="text-[13px] text-gray-500 mt-0.5 font-mono">{call.call_id}</p>
            <p className="text-[13px] text-gray-500 mt-1 flex items-center gap-2 flex-wrap">
              <span>
                Owner:{" "}
                {repNames.length > 0 ? (
                  <InlineSelectEdit
                    value={call.call_owner}
                    options={repNames}
                    emptyLabel="Unknown owner"
                    onSave={(v) => saveCallField("call_owner", v)}
                  />
                ) : (
                  <InlineTextEdit
                    value={call.call_owner}
                    placeholder="Call owner"
                    emptyLabel="Unknown owner"
                    inputClassName="text-[13px]"
                    onSave={(v) => saveCallField("call_owner", v)}
                  />
                )}
              </span>
              <span className="text-gray-300">·</span>
              <span>
                Result:{" "}
                <InlineTextEdit
                  value={call.call_result}
                  placeholder="Call result"
                  emptyLabel="No result"
                  inputClassName="text-[13px]"
                  onSave={(v) => saveCallField("call_result", v)}
                />
              </span>
              {call.processed_date && (
                <span className="text-[11px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200">
                  Processed
                </span>
              )}
              <ProvenanceBadge source={call.source} />
            </p>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <button
              type="button"
              onClick={() => void downloadTranscript(call.call_id)}
              className="text-[13px] font-medium text-accent-600 hover:text-accent-700 underline underline-offset-2"
            >
              Download transcript
            </button>
            <Button variant="ai" size="sm" onClick={() => void handleReanalyze()} disabled={isReanalyzing}>
              {isReanalyzing ? (
                "Re-analyzing…"
              ) : (
                <>
                  <SparkleIcon />
                  Re-analyze
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Re-analyzing banner */}
        {isReanalyzing && (
          <div className="flex items-center gap-3 bg-amber-50 border border-amber-200 rounded-lg px-4 py-3">
            <svg
              className="animate-spin w-4 h-4 text-amber-600 shrink-0"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            <p className="text-[13px] text-amber-800">
              Re-analyzing this call… the existing summary and insights below will update once the new run finishes.
            </p>
          </div>
        )}

        {/* Analysis sections — dimmed while re-analyzing.
            isProcessing = first-pass analyzer hasn't written processed_date
            yet. Distinct from isReanalyzing (manual re-run on an already-
            processed call). Drives the "Analyzing…" placeholder below. */}
        <div className={`space-y-6 transition-opacity ${isReanalyzing ? "opacity-60 pointer-events-none" : ""}`}>
          {/* Summary — editable */}
          <section className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <h2 className="text-[15px] font-bold text-gray-900 mb-2">Summary</h2>
            <InlineTextareaEdit
              value={call.summary}
              rows={6}
              className="text-[15px] text-gray-700"
              emptyMessage={
                isProcessing ? (
                  <div className="flex items-center gap-2 text-[13px] text-amber-700">
                    <svg
                      className="animate-spin w-3.5 h-3.5 text-amber-600 shrink-0"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                    >
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    <span>Analyzing the transcript… summary will appear here once the run finishes.</span>
                  </div>
                ) : (
                  <p className="text-[13px] text-gray-400 italic">
                    No summary yet. Click to write one, or run Re-analyze if the analyzer hasn&apos;t run.
                  </p>
                )
              }
              onSave={(v) => saveCallField("summary", v)}
            />
          </section>

          {/* Insights — editable + deletable */}
          <section className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
            <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100">
              <h2 className="text-[15px] font-bold text-gray-900">Insights</h2>
              <span className="text-[13px] text-gray-400">{insights.length}</span>
            </div>
            {insights.length === 0 ? (
              isProcessing ? (
                <div className="px-5 py-6 flex items-center gap-2 text-[13px] text-amber-700">
                  <svg
                    className="animate-spin w-3.5 h-3.5 text-amber-600 shrink-0"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                  >
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  <span>Analyzing the transcript… insights will appear here once the run finishes.</span>
                </div>
              ) : (
                <div className="px-5 py-6 text-[13px] text-gray-400 italic">No insights extracted yet.</div>
              )
            ) : (
              <div className="divide-y divide-gray-100">
                {insights.map((ins) => (
                  <InsightRow
                    key={ins.insight_id}
                    insight={ins}
                    onSaveField={(field, value) => saveInsightField(ins.insight_id, field, value)}
                    onDelete={() => void deleteInsight(ins.insight_id)}
                  />
                ))}
              </div>
            )}
          </section>

          {/* Content ideas — full briefs generated from this call's insights.
              Read-only here; the content team works them on the Content Ideas page. */}
          {content_ideas.length > 0 && (
            <section className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
              <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100">
                <h2 className="text-[15px] font-bold text-gray-900">Content ideas</h2>
                <span className="text-[13px] text-gray-400">{content_ideas.length}</span>
              </div>
              <div className="divide-y divide-gray-100">
                {content_ideas.map((idea) => (
                  <ContentIdeaCard key={idea.content_id} idea={idea} />
                ))}
              </div>
            </section>
          )}
        </div>

        {/* Transcript — read-only */}
        <section className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
          <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100">
            <h2 className="text-[15px] font-bold text-gray-900">Transcript</h2>
            <span className="text-[13px] text-gray-400">
              {call.transcript ? `${call.transcript.length.toLocaleString()} chars` : "—"}
            </span>
          </div>
          {call.transcript ? (
            <pre className="px-5 py-4 text-[13px] text-gray-700 whitespace-pre-wrap font-sans leading-relaxed max-h-96 overflow-y-auto">
              {call.transcript}
            </pre>
          ) : (
            <div className="px-5 py-6 text-[13px] text-gray-400 italic">No transcript on file.</div>
          )}
        </section>
      </main>

      <ConfirmDialog
        open={pendingDeleteInsightId !== null}
        onClose={() => setPendingDeleteInsightId(null)}
        onConfirm={() => void confirmDeleteInsight()}
        title="Delete this insight?"
        description="This cannot be undone."
        confirmLabel="Delete"
        variant="danger"
        loading={isDeletingInsight}
      />
    </>
  );
}
