"""add sprint3 marketing tables

Revision ID: 99e593e5b25e
Revises: 
Create Date: 2026-04-08 19:14:24.637022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99e593e5b25e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('campaign_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipients_count', sa.Integer(), nullable=False),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('unsubscribe_count', sa.Integer(), nullable=False),
    sa.Column('bounce_count', sa.Integer(), nullable=False),
    sa.Column('open_rate', sa.Float(), nullable=True),
    sa.Column('click_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funnel_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funnel_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_events_event_type'), 'funnel_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_funnel_events_funnel_id'), 'funnel_events', ['funnel_id'], unique=False)
    op.create_index(op.f('ix_funnel_events_stage'), 'funnel_events', ['stage'], unique=False)
    op.create_table('funnel_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funnel_id', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funnel_id', 'stage', 'period_start', name='uq_funnel_stats_funnel_stage_period')
    )
    op.create_index(op.f('ix_funnel_stats_funnel_id'), 'funnel_stats', ['funnel_id'], unique=False)
    op.create_table('icp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('demographics', sa.Text(), nullable=True),
    sa.Column('psychographics', sa.Text(), nullable=True),
    sa.Column('pain_summary', sa.Text(), nullable=True),
    sa.Column('goal_summary', sa.Text(), nullable=True),
    sa.Column('buying_triggers', sa.Text(), nullable=True),
    sa.Column('common_objections', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icp_segment'), 'icp', ['segment'], unique=False)
    op.create_table('social_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('commented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_comments_platform'), 'social_comments', ['platform'], unique=False)
    op.create_table('social_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_stats_platform'), 'social_stats', ['platform'], unique=False)
    op.alter_column('audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audit_log', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('audit_log', 'table_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('audit_log', 'record_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('audit_log', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_audit_log_action'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_table'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_user'), table_name='audit_log')
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_table_name'), 'audit_log', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.alter_column('business_profile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('calls', sa.Column('video_url_hash', sa.String(length=64), nullable=True))
    op.add_column('calls', sa.Column('transcript_text', sa.Text(), nullable=True))
    op.alter_column('calls', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('calls', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('calls', 'call_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('calls', 'call_result',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('calls', 'transcript_source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('calls', 'transcript_quality',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('calls', 'transcript_link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('calls', 'processed_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('calls', 'call_duration_minutes',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_calls_call_type'), table_name='calls')
    op.drop_index(op.f('idx_calls_date'), table_name='calls')
    op.drop_index(op.f('idx_calls_lead'), table_name='calls')
    op.drop_index(op.f('idx_calls_member'), table_name='calls')
    op.drop_index(op.f('idx_calls_transcript_uid'), table_name='calls')
    op.create_index(op.f('ix_calls_call_type'), 'calls', ['call_type'], unique=False)
    op.create_index(op.f('ix_calls_lead_id'), 'calls', ['lead_id'], unique=False)
    op.create_index(op.f('ix_calls_member_id'), 'calls', ['member_id'], unique=False)
    op.create_index(op.f('ix_calls_video_url_hash'), 'calls', ['video_url_hash'], unique=True)
    op.drop_constraint(op.f('calls_member_id_fkey'), 'calls', type_='foreignkey')
    op.drop_constraint(op.f('calls_lead_id_fkey'), 'calls', type_='foreignkey')
    op.create_foreign_key(None, 'calls', 'members', ['member_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'calls', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    op.alter_column('content_ideas', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('content_ideas', 'insight_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('content_ideas', 'call_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('content_ideas', 'source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('content_ideas', 'content_format',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('content_ideas', 'content_angle',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('content_ideas', 'priority_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('content_ideas', 'best_platform',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('content_ideas', 'idea_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('content_ideas', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('content_ideas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_content_ideas_format'), table_name='content_ideas')
    op.drop_index(op.f('idx_content_ideas_insight_id'), table_name='content_ideas')
    op.drop_index(op.f('idx_content_ideas_status'), table_name='content_ideas')
    op.create_index(op.f('ix_content_ideas_call_id'), 'content_ideas', ['call_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_insight_id'), 'content_ideas', ['insight_id'], unique=False)
    op.alter_column('error_log', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('error_log', 'error_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('error_log', 'severity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('error_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_error_log_agent_id'), table_name='error_log')
    op.drop_index(op.f('idx_error_log_created_at'), table_name='error_log')
    op.drop_index(op.f('idx_error_log_error_code'), table_name='error_log')
    op.drop_index(op.f('idx_error_log_request_id'), table_name='error_log')
    op.drop_index(op.f('idx_error_log_severity'), table_name='error_log')
    op.drop_index(op.f('idx_error_log_user_id'), table_name='error_log')
    op.create_index(op.f('ix_error_log_agent_id'), 'error_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_error_log_created_at'), 'error_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_log_error_code'), 'error_log', ['error_code'], unique=False)
    op.create_index(op.f('ix_error_log_request_id'), 'error_log', ['request_id'], unique=False)
    op.create_index(op.f('ix_error_log_severity'), 'error_log', ['severity'], unique=False)
    op.create_index(op.f('ix_error_log_user_id'), 'error_log', ['user_id'], unique=False)
    op.alter_column('goals', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goals', 'goal_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('goals', 'target_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('goals', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_goals_lead'), table_name='goals')
    op.drop_index(op.f('idx_goals_member'), table_name='goals')
    op.drop_index(op.f('idx_goals_status'), table_name='goals')
    op.create_index(op.f('ix_goals_lead_id'), 'goals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_goals_member_id'), 'goals', ['member_id'], unique=False)
    op.alter_column('idempotency_keys', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('idempotency_keys', 'operation_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('idempotency_keys_operation_key_key'), 'idempotency_keys', type_='unique')
    op.drop_index(op.f('idx_idempotency_keys_created_at'), table_name='idempotency_keys')
    op.create_index(op.f('ix_idempotency_keys_operation_key'), 'idempotency_keys', ['operation_key'], unique=True)
    op.alter_column('insight_tags', 'insight_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=True)
    op.alter_column('insight_tags', 'tag',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=True)
    op.alter_column('insight_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_insight_tags_insight'), table_name='insight_tags')
    op.drop_index(op.f('idx_insight_tags_tag'), table_name='insight_tags')
    op.create_index(op.f('ix_insight_tags_insight_id'), 'insight_tags', ['insight_id'], unique=False)
    op.create_index(op.f('ix_insight_tags_tag'), 'insight_tags', ['tag'], unique=False)
    op.drop_constraint(op.f('insight_tags_tag_fkey'), 'insight_tags', type_='foreignkey')
    op.create_foreign_key(None, 'insight_tags', 'tag_dictionary', ['tag'], ['tag'], ondelete='CASCADE')
    op.alter_column('insights', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('insights', 'call_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=True)
    op.alter_column('insights', 'insight_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('insights', 'signal_family',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('insights', 'signal',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('insights', 'signal_strength',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('insights', 'pain_layer',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('insights', 'best_use_case',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('insights', 'quote_confidence',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('insights', 'frequency_score',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('insights', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_insights_call'), table_name='insights')
    op.drop_index(op.f('idx_insights_created_at'), table_name='insights')
    op.drop_index(op.f('idx_insights_family'), table_name='insights')
    op.drop_index(op.f('idx_insights_insight_type'), table_name='insights')
    op.drop_index(op.f('idx_insights_signal'), table_name='insights')
    op.drop_index(op.f('idx_insights_strength'), table_name='insights')
    op.create_index(op.f('ix_insights_call_id'), 'insights', ['call_id'], unique=False)
    op.create_index(op.f('ix_insights_insight_type'), 'insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_insights_signal_family'), 'insights', ['signal_family'], unique=False)
    op.add_column('leads', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('leads', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leads', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('leads', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('leads', 'source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_leads_created_at'), table_name='leads')
    op.drop_index(op.f('idx_leads_source'), table_name='leads')
    op.drop_index(op.f('idx_leads_status'), table_name='leads')
    op.drop_constraint(op.f('leads_email_key'), 'leads', type_='unique')
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    op.alter_column('market_signals', 'signal_family',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('market_signals', 'signal',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('market_signals', 'insight_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('market_signals', 'total_mentions',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('market_signals', 'last_30_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('market_signals', 'last_7_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('market_signals', 'example_call_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('market_signals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_market_signals_family'), table_name='market_signals')
    op.create_index(op.f('ix_market_signals_signal'), 'market_signals', ['signal'], unique=False)
    op.create_index(op.f('ix_market_signals_signal_family'), 'market_signals', ['signal_family'], unique=False)
    op.alter_column('members', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('members', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('members', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_members_coach_id'), table_name='members')
    op.drop_index(op.f('idx_members_status'), table_name='members')
    op.drop_constraint(op.f('members_email_key'), 'members', type_='unique')
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.alter_column('monthly_preferences', 'sending_days',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('monthly_preferences', 'email_types',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('monthly_preferences', 'active_offers',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('monthly_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('monthly_preferences_month_year_key'), 'monthly_preferences', type_='unique')
    op.create_unique_constraint('uq_monthly_preferences_month_year', 'monthly_preferences', ['month', 'year'])
    op.alter_column('objections', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('objections', 'objection_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('objections', 'context',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('objections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_objections_lead'), table_name='objections')
    op.create_index(op.f('ix_objections_lead_id'), 'objections', ['lead_id'], unique=False)
    op.alter_column('offers', 'offer_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('offers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('offers', 'offer_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('offers', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('offers', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pain_points', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pain_points', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('pain_points', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('pain_points', 'frequency_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('pain_points', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_pain_points_category'), table_name='pain_points')
    op.drop_index(op.f('idx_pain_points_lead'), table_name='pain_points')
    op.drop_index(op.f('idx_pain_points_member'), table_name='pain_points')
    op.create_index(op.f('ix_pain_points_lead_id'), 'pain_points', ['lead_id'], unique=False)
    op.create_index(op.f('ix_pain_points_member_id'), 'pain_points', ['member_id'], unique=False)
    op.alter_column('sync_log', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sync_log', 'operation',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('sync_log', 'table_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('sync_log', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('sync_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_sync_log_created_at'), table_name='sync_log')
    op.drop_index(op.f('idx_sync_log_operation'), table_name='sync_log')
    op.drop_index(op.f('idx_sync_log_status'), table_name='sync_log')
    op.create_index(op.f('ix_sync_log_created_at'), 'sync_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_log_operation'), 'sync_log', ['operation'], unique=False)
    op.create_index(op.f('ix_sync_log_status'), 'sync_log', ['status'], unique=False)
    op.alter_column('tag_dictionary', 'tag',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('tag_dictionary', 'tag_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('tag_dictionary', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('teams', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teams', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('wins', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wins', 'win_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('wins', 'win_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('wins', 'impact_area',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('wins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_wins_member'), table_name='wins')
    op.create_index(op.f('ix_wins_member_id'), 'wins', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wins_member_id'), table_name='wins')
    op.create_index(op.f('idx_wins_member'), 'wins', ['member_id'], unique=False)
    op.alter_column('wins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('wins', 'impact_area',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('wins', 'win_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('wins', 'win_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('wins', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('teams', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('teams', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('tag_dictionary', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tag_dictionary', 'tag_type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('tag_dictionary', 'tag',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_sync_log_status'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_operation'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_created_at'), table_name='sync_log')
    op.create_index(op.f('idx_sync_log_status'), 'sync_log', ['status'], unique=False)
    op.create_index(op.f('idx_sync_log_operation'), 'sync_log', ['operation'], unique=False)
    op.create_index(op.f('idx_sync_log_created_at'), 'sync_log', ['created_at'], unique=False)
    op.alter_column('sync_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sync_log', 'status',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('sync_log', 'table_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('sync_log', 'operation',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('sync_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_pain_points_member_id'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_lead_id'), table_name='pain_points')
    op.create_index(op.f('idx_pain_points_member'), 'pain_points', ['member_id'], unique=False)
    op.create_index(op.f('idx_pain_points_lead'), 'pain_points', ['lead_id'], unique=False)
    op.create_index(op.f('idx_pain_points_category'), 'pain_points', ['category'], unique=False)
    op.alter_column('pain_points', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pain_points', 'frequency_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('pain_points', 'category',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('pain_points', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('pain_points', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('offers', 'url',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('offers', 'status',
               existing_type=sa.String(length=64),
               server_default=sa.text("'Active'::character varying"),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('offers', 'offer_type',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('offers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('offers', 'offer_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_objections_lead_id'), table_name='objections')
    op.create_index(op.f('idx_objections_lead'), 'objections', ['lead_id'], unique=False)
    op.alter_column('objections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('objections', 'context',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('objections', 'objection_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('objections', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint('uq_monthly_preferences_month_year', 'monthly_preferences', type_='unique')
    op.create_unique_constraint(op.f('monthly_preferences_month_year_key'), 'monthly_preferences', ['month', 'year'], postgresql_nulls_not_distinct=False)
    op.alter_column('monthly_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('monthly_preferences', 'active_offers',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('monthly_preferences', 'email_types',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('monthly_preferences', 'sending_days',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.create_unique_constraint(op.f('members_email_key'), 'members', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_members_status'), 'members', ['status'], unique=False)
    op.create_index(op.f('idx_members_coach_id'), 'members', ['coach_id'], unique=False)
    op.alter_column('members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('members', 'status',
               existing_type=sa.String(length=64),
               server_default=sa.text("'active'::character varying"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('members', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('members', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_market_signals_signal_family'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_signal'), table_name='market_signals')
    op.create_index(op.f('idx_market_signals_family'), 'market_signals', ['signal_family'], unique=False)
    op.alter_column('market_signals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('market_signals', 'example_call_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('market_signals', 'last_7_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('market_signals', 'last_30_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('market_signals', 'total_mentions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('market_signals', 'insight_type',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('market_signals', 'signal',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('market_signals', 'signal_family',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.create_unique_constraint(op.f('leads_email_key'), 'leads', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('idx_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('idx_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('leads', 'source',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('leads', 'status',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('leads', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('leads', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('leads', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('leads', 'notes')
    op.drop_index(op.f('ix_insights_signal_family'), table_name='insights')
    op.drop_index(op.f('ix_insights_insight_type'), table_name='insights')
    op.drop_index(op.f('ix_insights_call_id'), table_name='insights')
    op.create_index(op.f('idx_insights_strength'), 'insights', ['signal_strength'], unique=False)
    op.create_index(op.f('idx_insights_signal'), 'insights', ['signal'], unique=False)
    op.create_index(op.f('idx_insights_insight_type'), 'insights', ['insight_type'], unique=False)
    op.create_index(op.f('idx_insights_family'), 'insights', ['signal_family'], unique=False)
    op.create_index(op.f('idx_insights_created_at'), 'insights', ['created_at'], unique=False)
    op.create_index(op.f('idx_insights_call'), 'insights', ['call_id'], unique=False)
    op.alter_column('insights', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('insights', 'frequency_score',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('insights', 'quote_confidence',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('insights', 'best_use_case',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('insights', 'pain_layer',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('insights', 'signal_strength',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('insights', 'signal',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('insights', 'signal_family',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('insights', 'insight_type',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('insights', 'call_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('insights', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'insight_tags', type_='foreignkey')
    op.create_foreign_key(op.f('insight_tags_tag_fkey'), 'insight_tags', 'tag_dictionary', ['tag'], ['tag'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_insight_tags_tag'), table_name='insight_tags')
    op.drop_index(op.f('ix_insight_tags_insight_id'), table_name='insight_tags')
    op.create_index(op.f('idx_insight_tags_tag'), 'insight_tags', ['tag'], unique=False)
    op.create_index(op.f('idx_insight_tags_insight'), 'insight_tags', ['insight_id'], unique=False)
    op.alter_column('insight_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('insight_tags', 'tag',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('insight_tags', 'insight_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_idempotency_keys_operation_key'), table_name='idempotency_keys')
    op.create_index(op.f('idx_idempotency_keys_created_at'), 'idempotency_keys', ['created_at'], unique=False)
    op.create_unique_constraint(op.f('idempotency_keys_operation_key_key'), 'idempotency_keys', ['operation_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('idempotency_keys', 'operation_key',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('idempotency_keys', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_goals_member_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_lead_id'), table_name='goals')
    op.create_index(op.f('idx_goals_status'), 'goals', ['status'], unique=False)
    op.create_index(op.f('idx_goals_member'), 'goals', ['member_id'], unique=False)
    op.create_index(op.f('idx_goals_lead'), 'goals', ['lead_id'], unique=False)
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('goals', 'status',
               existing_type=sa.String(length=64),
               server_default=sa.text("'active'::character varying"),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('goals', 'target_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('goals', 'goal_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('goals', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_error_log_user_id'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_severity'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_request_id'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_error_code'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_created_at'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_agent_id'), table_name='error_log')
    op.create_index(op.f('idx_error_log_user_id'), 'error_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_error_log_severity'), 'error_log', ['severity'], unique=False)
    op.create_index(op.f('idx_error_log_request_id'), 'error_log', ['request_id'], unique=False)
    op.create_index(op.f('idx_error_log_error_code'), 'error_log', ['error_code'], unique=False)
    op.create_index(op.f('idx_error_log_created_at'), 'error_log', ['created_at'], unique=False)
    op.create_index(op.f('idx_error_log_agent_id'), 'error_log', ['agent_id'], unique=False)
    op.alter_column('error_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('error_log', 'severity',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('error_log', 'error_code',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('error_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_content_ideas_insight_id'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_call_id'), table_name='content_ideas')
    op.create_index(op.f('idx_content_ideas_status'), 'content_ideas', ['status'], unique=False)
    op.create_index(op.f('idx_content_ideas_insight_id'), 'content_ideas', ['insight_id'], unique=False)
    op.create_index(op.f('idx_content_ideas_format'), 'content_ideas', ['content_format'], unique=False)
    op.alter_column('content_ideas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('content_ideas', 'status',
               existing_type=sa.String(length=64),
               server_default=sa.text("'Idea'::character varying"),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('content_ideas', 'idea_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('content_ideas', 'best_platform',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('content_ideas', 'priority_level',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('content_ideas', 'content_angle',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('content_ideas', 'content_format',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('content_ideas', 'source',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('content_ideas', 'call_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('content_ideas', 'insight_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('content_ideas', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.create_foreign_key(op.f('calls_lead_id_fkey'), 'calls', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('calls_member_id_fkey'), 'calls', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_calls_video_url_hash'), table_name='calls')
    op.drop_index(op.f('ix_calls_member_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_lead_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_type'), table_name='calls')
    op.create_index(op.f('idx_calls_transcript_uid'), 'calls', ['transcript_uid'], unique=False)
    op.create_index(op.f('idx_calls_member'), 'calls', ['member_id'], unique=False)
    op.create_index(op.f('idx_calls_lead'), 'calls', ['lead_id'], unique=False)
    op.create_index(op.f('idx_calls_date'), 'calls', ['date'], unique=False)
    op.create_index(op.f('idx_calls_call_type'), 'calls', ['call_type'], unique=False)
    op.alter_column('calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('calls', 'call_duration_minutes',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('calls', 'processed_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('calls', 'transcript_link',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('calls', 'transcript_quality',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('calls', 'transcript_source',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('calls', 'call_result',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('calls', 'call_type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('calls', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('calls', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('calls', 'transcript_text')
    op.drop_column('calls', 'video_url_hash')
    op.alter_column('business_profile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_table_name'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.create_index(op.f('idx_audit_log_user'), 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_log_table'), 'audit_log', ['table_name'], unique=False)
    op.create_index(op.f('idx_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('audit_log', 'ip_address',
               existing_type=sa.String(length=64),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('audit_log', 'record_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_log', 'table_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('audit_log', 'action',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_social_stats_platform'), table_name='social_stats')
    op.drop_table('social_stats')
    op.drop_index(op.f('ix_social_comments_platform'), table_name='social_comments')
    op.drop_table('social_comments')
    op.drop_index(op.f('ix_icp_segment'), table_name='icp')
    op.drop_table('icp')
    op.drop_index(op.f('ix_funnel_stats_funnel_id'), table_name='funnel_stats')
    op.drop_table('funnel_stats')
    op.drop_index(op.f('ix_funnel_events_stage'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_funnel_id'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_event_type'), table_name='funnel_events')
    op.drop_table('funnel_events')
    op.drop_table('email_campaigns')
    # ### end Alembic commands ###
