"""wgr subsystems: sales/coaching/revenue/webinar tables + call provenance

Revision ID: aa7e787e302d
Revises: c4049d9dcf4c
Create Date: 2026-06-18 02:10:30.007693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa7e787e302d'
down_revision: Union[str, None] = 'c4049d9dcf4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opt_in_events',
    sa.Column('opt_in_event_id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('utm_source', sa.String(length=128), nullable=True),
    sa.Column('utm_medium', sa.String(length=128), nullable=True),
    sa.Column('utm_campaign', sa.String(length=256), nullable=True),
    sa.Column('utm_content', sa.String(length=256), nullable=True),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('opt_in_event_id')
    )
    op.create_index(op.f('ix_opt_in_events_lead_id'), 'opt_in_events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_opt_in_events_occurred_at'), 'opt_in_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_opt_in_events_source'), 'opt_in_events', ['source'], unique=False)
    op.create_table('sales_reps',
    sa.Column('rep_id', sa.String(length=128), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('ghl_user_id', sa.Text(), nullable=True),
    sa.Column('slack_user_id', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('probation_start_date', sa.Date(), nullable=True),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('current_tier_access', sa.Integer(), nullable=True),
    sa.Column('historical_aliases', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('capabilities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('hired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rep_id')
    )
    op.create_index(op.f('ix_sales_reps_business_id'), 'sales_reps', ['business_id'], unique=False)
    op.create_table('sales_scorecard_categories',
    sa.Column('category_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('applies_to', sa.String(length=64), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('sales_strike_rules',
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('strike_type', sa.String(length=64), nullable=True),
    sa.Column('call_type', sa.String(length=64), nullable=True),
    sa.Column('threshold_score', sa.Numeric(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=64), nullable=True),
    sa.Column('applies_to_roles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('webinar_engagements',
    sa.Column('engagement_id', sa.String(length=128), nullable=False),
    sa.Column('lead_id', sa.String(length=128), nullable=True),
    sa.Column('ghl_contact_id', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('watched_live', sa.Boolean(), nullable=False),
    sa.Column('time_live_seconds', sa.Integer(), nullable=True),
    sa.Column('watched_replay', sa.Boolean(), nullable=False),
    sa.Column('time_replay_seconds', sa.Integer(), nullable=True),
    sa.Column('total_watched', sa.Boolean(), nullable=False),
    sa.Column('utm_source', sa.String(length=128), nullable=True),
    sa.Column('utm_medium', sa.String(length=128), nullable=True),
    sa.Column('utm_campaign', sa.String(length=256), nullable=True),
    sa.Column('utm_content', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('engagement_id')
    )
    op.create_index(op.f('ix_webinar_engagements_lead_id'), 'webinar_engagements', ['lead_id'], unique=False)
    op.create_table('closed_sales',
    sa.Column('sale_id', sa.String(length=128), nullable=False),
    sa.Column('lead_id', sa.String(length=128), nullable=True),
    sa.Column('ghl_contact_id', sa.String(length=128), nullable=True),
    sa.Column('offer_id', sa.String(length=128), nullable=True),
    sa.Column('rep_id', sa.String(length=128), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('amount_collected', sa.Numeric(), nullable=True),
    sa.Column('revenue_earned', sa.Numeric(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('time_to_close_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rep_id'], ['sales_reps.rep_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_index(op.f('ix_closed_sales_close_date'), 'closed_sales', ['close_date'], unique=False)
    op.create_index(op.f('ix_closed_sales_lead_id'), 'closed_sales', ['lead_id'], unique=False)
    op.create_index(op.f('ix_closed_sales_offer_id'), 'closed_sales', ['offer_id'], unique=False)
    op.create_index(op.f('ix_closed_sales_rep_id'), 'closed_sales', ['rep_id'], unique=False)
    op.create_table('sales_activities',
    sa.Column('activity_id', sa.String(length=128), nullable=False),
    sa.Column('rep_id', sa.String(length=128), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.String(length=128), nullable=True),
    sa.Column('activity_type', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('ghl_event_type', sa.String(length=128), nullable=True),
    sa.Column('ghl_resource_id', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rep_id'], ['sales_reps.rep_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_sales_activities_activity_type'), 'sales_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_sales_activities_lead_id'), 'sales_activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_sales_activities_occurred_at'), 'sales_activities', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_sales_activities_rep_id'), 'sales_activities', ['rep_id'], unique=False)
    op.create_table('sales_call_scores',
    sa.Column('score_id', sa.String(length=128), nullable=False),
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.String(length=128), nullable=True),
    sa.Column('rep_id', sa.String(length=128), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['sales_scorecard_categories.category_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rep_id'], ['sales_reps.rep_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_index(op.f('ix_sales_call_scores_call_id'), 'sales_call_scores', ['call_id'], unique=False)
    op.create_index(op.f('ix_sales_call_scores_category_id'), 'sales_call_scores', ['category_id'], unique=False)
    op.create_index(op.f('ix_sales_call_scores_rep_id'), 'sales_call_scores', ['rep_id'], unique=False)
    op.create_table('sales_coaching_strikes',
    sa.Column('strike_id', sa.String(length=128), nullable=False),
    sa.Column('rep_id', sa.String(length=128), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.String(length=128), nullable=True),
    sa.Column('category_id', sa.String(length=128), nullable=True),
    sa.Column('call_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rep_id'], ['sales_reps.rep_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['sales_reps.rep_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['sales_strike_rules.rule_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('strike_id')
    )
    op.create_index(op.f('ix_sales_coaching_strikes_rep_id'), 'sales_coaching_strikes', ['rep_id'], unique=False)
    op.create_table('sales_eod_reports',
    sa.Column('report_id', sa.String(length=128), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=32), nullable=True),
    sa.Column('rep_id', sa.String(length=128), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slack_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slack_message_ts', sa.String(length=64), nullable=True),
    sa.Column('slack_channel', sa.String(length=128), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rep_id'], ['sales_reps.rep_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_sales_eod_reports_rep_id'), 'sales_eod_reports', ['rep_id'], unique=False)
    op.create_index(op.f('ix_sales_eod_reports_report_date'), 'sales_eod_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_sales_eod_reports_report_type'), 'sales_eod_reports', ['report_type'], unique=False)
    op.create_table('sales_strike_actions',
    sa.Column('action_id', sa.String(length=128), nullable=False),
    sa.Column('strike_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strike_id'], ['sales_coaching_strikes.strike_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_sales_strike_actions_strike_id'), 'sales_strike_actions', ['strike_id'], unique=False)
    op.create_table('sales_strike_evidence',
    sa.Column('evidence_id', sa.String(length=128), nullable=False),
    sa.Column('strike_id', sa.String(length=128), nullable=False),
    sa.Column('call_score_id', sa.String(length=128), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_score_id'], ['sales_call_scores.score_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strike_id'], ['sales_coaching_strikes.strike_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_sales_strike_evidence_strike_id'), 'sales_strike_evidence', ['strike_id'], unique=False)

    # Call provenance columns for WGR-sourced calls (idempotent dedup on external_id).
    op.add_column('calls', sa.Column('source', sa.String(length=128), nullable=True))
    op.add_column('calls', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_calls_external_id'), 'calls', ['external_id'], unique=False)
    op.create_index(op.f('ix_calls_source'), 'calls', ['source'], unique=False)
    # NOTE: autogenerate also proposed dropping ~11 existing hand-crafted indexes
    # (audit_log/chat/email/embeddings/google/lead_notes composite, GIN & partial
    # indexes) and the uq_leads/uq_email_campaigns dedup constraints, plus an
    # integrations.status default change — none of which this change touches. Those
    # were created by raw-SQL migrations the ORM metadata doesn't model, so
    # autogenerate can't see them. They are intentionally OMITTED here so this
    # migration only adds the new WGR tables + Call columns.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_source'), table_name='calls')
    op.drop_index(op.f('ix_calls_external_id'), table_name='calls')
    op.drop_column('calls', 'external_id')
    op.drop_column('calls', 'source')
    op.drop_index(op.f('ix_sales_strike_evidence_strike_id'), table_name='sales_strike_evidence')
    op.drop_table('sales_strike_evidence')
    op.drop_index(op.f('ix_sales_strike_actions_strike_id'), table_name='sales_strike_actions')
    op.drop_table('sales_strike_actions')
    op.drop_index(op.f('ix_sales_eod_reports_report_type'), table_name='sales_eod_reports')
    op.drop_index(op.f('ix_sales_eod_reports_report_date'), table_name='sales_eod_reports')
    op.drop_index(op.f('ix_sales_eod_reports_rep_id'), table_name='sales_eod_reports')
    op.drop_table('sales_eod_reports')
    op.drop_index(op.f('ix_sales_coaching_strikes_rep_id'), table_name='sales_coaching_strikes')
    op.drop_table('sales_coaching_strikes')
    op.drop_index(op.f('ix_sales_call_scores_rep_id'), table_name='sales_call_scores')
    op.drop_index(op.f('ix_sales_call_scores_category_id'), table_name='sales_call_scores')
    op.drop_index(op.f('ix_sales_call_scores_call_id'), table_name='sales_call_scores')
    op.drop_table('sales_call_scores')
    op.drop_index(op.f('ix_sales_activities_rep_id'), table_name='sales_activities')
    op.drop_index(op.f('ix_sales_activities_occurred_at'), table_name='sales_activities')
    op.drop_index(op.f('ix_sales_activities_lead_id'), table_name='sales_activities')
    op.drop_index(op.f('ix_sales_activities_activity_type'), table_name='sales_activities')
    op.drop_table('sales_activities')
    op.drop_index(op.f('ix_closed_sales_rep_id'), table_name='closed_sales')
    op.drop_index(op.f('ix_closed_sales_offer_id'), table_name='closed_sales')
    op.drop_index(op.f('ix_closed_sales_lead_id'), table_name='closed_sales')
    op.drop_index(op.f('ix_closed_sales_close_date'), table_name='closed_sales')
    op.drop_table('closed_sales')
    op.drop_index(op.f('ix_webinar_engagements_lead_id'), table_name='webinar_engagements')
    op.drop_table('webinar_engagements')
    op.drop_table('sales_strike_rules')
    op.drop_table('sales_scorecard_categories')
    op.drop_index(op.f('ix_sales_reps_business_id'), table_name='sales_reps')
    op.drop_table('sales_reps')
    op.drop_index(op.f('ix_opt_in_events_source'), table_name='opt_in_events')
    op.drop_index(op.f('ix_opt_in_events_occurred_at'), table_name='opt_in_events')
    op.drop_index(op.f('ix_opt_in_events_lead_id'), table_name='opt_in_events')
    op.drop_table('opt_in_events')
    # ### end Alembic commands ###
