"""add ads_stats dm_stats and promotions tables

Revision ID: ccffed696e99
Revises: 99e593e5b25e
Create Date: 2026-04-11 13:41:52.280719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccffed696e99'
down_revision: Union[str, None] = '99e593e5b25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_stats_platform'), 'ads_stats', ['platform'], unique=False)
    op.create_table('dm_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('outreach_sent', sa.Integer(), nullable=False),
    sa.Column('responses', sa.Integer(), nullable=False),
    sa.Column('positive_responses', sa.Integer(), nullable=False),
    sa.Column('meetings_booked', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_stats_platform'), 'dm_stats', ['platform'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('promo_type', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotions')
    op.drop_index(op.f('ix_dm_stats_platform'), table_name='dm_stats')
    op.drop_table('dm_stats')
    op.drop_index(op.f('ix_ads_stats_platform'), table_name='ads_stats')
    op.drop_table('ads_stats')
    # ### end Alembic commands ###
