"""add leads.entry_date — upstream funnel-entry date

CI's leads.created_at records when a row was synced into CI, not when the
lead actually entered the funnel. WGR carries the real entry_date per lead;
this column persists it so the /leads UI can show the true entry date and
sort by it. Nullable — most WGR leads have no upstream entry_date.

Hand-written (not autogenerated): autogenerate on this project emits
spurious drops of hand-crafted partial/GIN indexes the ORM doesn't model.

Revision ID: n5e6f7a8b9c0
Revises: aa7e787e302d
Create Date: 2026-06-22 00:00:00.000000
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "n5e6f7a8b9c0"
down_revision: Union[str, None] = "aa7e787e302d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("leads", sa.Column("entry_date", sa.Date(), nullable=True))
    op.create_index("ix_leads_entry_date", "leads", ["entry_date"])


def downgrade() -> None:
    op.drop_index("ix_leads_entry_date", table_name="leads")
    op.drop_column("leads", "entry_date")
