"""WGR marketing/social mirror: instagram_posts table + social_comments provenance

Wires four previously-empty CI tables to WGR's real data:
  * email_campaigns  — already has source/external_id; no schema change
  * insight_tags     — already keyed on WGR's int id; no schema change
  * social_comments  — add source/external_id (+ unique) for idempotent sync
  * instagram_posts  — NEW per-post table (distinct grain from social_stats)

Read-only mirror of WGR; CI never writes back upstream.

Hand-written (not autogenerated): autogenerate on this project emits spurious
drops of hand-crafted partial/GIN indexes the ORM metadata doesn't model.

Revision ID: o6f7a8b9c0d1
Revises: n5e6f7a8b9c0
Create Date: 2026-06-22 00:00:00.000000
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "o6f7a8b9c0d1"
down_revision: Union[str, None] = "n5e6f7a8b9c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- social_comments: provenance for idempotent WGR dedup ---------------
    op.add_column("social_comments", sa.Column("source", sa.String(32), nullable=True))
    op.add_column(
        "social_comments", sa.Column("external_id", sa.String(128), nullable=True)
    )
    op.create_index(
        "ix_social_comments_source", "social_comments", ["source"]
    )
    op.create_index(
        "ix_social_comments_external_id", "social_comments", ["external_id"]
    )
    op.create_unique_constraint(
        "uq_social_comments_source_external_id",
        "social_comments",
        ["source", "external_id"],
    )

    # --- instagram_posts: new per-post performance table -------------------
    op.create_table(
        "instagram_posts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("source", sa.String(32), nullable=True),
        sa.Column("external_id", sa.String(128), nullable=True),
        sa.Column("ig_media_id", sa.String(128), nullable=True),
        sa.Column("permalink", sa.String(1024), nullable=True),
        sa.Column("media_type", sa.String(64), nullable=True),
        sa.Column("is_reel", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("likes_count", sa.Integer(), nullable=True),
        sa.Column("comments_count", sa.Integer(), nullable=True),
        sa.Column("saves_count", sa.Integer(), nullable=True),
        sa.Column("shares_count", sa.Integer(), nullable=True),
        sa.Column("reach", sa.Integer(), nullable=True),
        sa.Column("views", sa.Integer(), nullable=True),
        sa.Column("avg_watch_time_sec", sa.Integer(), nullable=True),
        sa.Column("engagement_rate", sa.Float(), nullable=True),
        sa.Column("content_pillar", sa.String(128), nullable=True),
        sa.Column("hook_text", sa.Text(), nullable=True),
        sa.Column("hook_type", sa.String(128), nullable=True),
        sa.Column("script_transcript", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "source", "external_id", name="uq_instagram_posts_source_external_id"
        ),
    )
    op.create_index("ix_instagram_posts_source", "instagram_posts", ["source"])
    op.create_index(
        "ix_instagram_posts_external_id", "instagram_posts", ["external_id"]
    )
    op.create_index("ix_instagram_posts_posted_at", "instagram_posts", ["posted_at"])


def downgrade() -> None:
    op.drop_table("instagram_posts")
    op.drop_constraint(
        "uq_social_comments_source_external_id", "social_comments", type_="unique"
    )
    op.drop_index("ix_social_comments_external_id", table_name="social_comments")
    op.drop_index("ix_social_comments_source", table_name="social_comments")
    op.drop_column("social_comments", "external_id")
    op.drop_column("social_comments", "source")
