"""add rep_overrides table

Revision ID: p7a8b9c0d1e2
Revises: o6f7a8b9c0d1
Create Date: 2026-06-29

CI-owned editable overrides for synced reps (sales_reps). The Members page edits
write here so they survive the WGR sync. Hand-written (not autogenerated) to
avoid the unrelated-index drift autogenerate proposes on this DB.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "p7a8b9c0d1e2"
down_revision: Union[str, None] = "o6f7a8b9c0d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "rep_overrides",
        sa.Column("rep_id", sa.String(length=128), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("role", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["rep_id"], ["sales_reps.rep_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rep_id"),
    )


def downgrade() -> None:
    op.drop_table("rep_overrides")
