"""add metric_snapshots table

Revision ID: q8b9c0d1e2f3
Revises: p7a8b9c0d1e2
Create Date: 2026-06-29

The metric snapshot timeseries store — foundation of the data-intelligence engine
(New Documents/north-star-data-intelligence.md). Append-only history of every
registered outcome metric, so we can track progress as more data accrues.
Hand-written (not autogenerated) to avoid the unrelated-index drift autogenerate
proposes on this DB.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "q8b9c0d1e2f3"
down_revision: Union[str, None] = "p7a8b9c0d1e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "metric_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("metric_key", sa.String(length=128), nullable=False),
        sa.Column("area", sa.String(length=32), nullable=False),
        sa.Column("window", sa.String(length=16), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False, server_default="global"),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column(
            "captured_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "metric_key",
            "window",
            "scope",
            "captured_date",
            name="uq_metric_snapshots_key_window_scope_date",
        ),
    )
    op.create_index(
        op.f("ix_metric_snapshots_metric_key"), "metric_snapshots", ["metric_key"], unique=False
    )
    op.create_index(op.f("ix_metric_snapshots_area"), "metric_snapshots", ["area"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_metric_snapshots_area"), table_name="metric_snapshots")
    op.drop_index(op.f("ix_metric_snapshots_metric_key"), table_name="metric_snapshots")
    op.drop_table("metric_snapshots")
