"""add scope to recommendations

Revision ID: v3a4b5c6d7e8
Revises: u2f3a4b5c6d7
Create Date: 2026-07-09

Rep-scoped recommendations (data-intelligence engine, PR 1/3 of the per-rep
scope + channel-mix metrics work). Mirrors metric_snapshots.scope: 'global' for
the existing company-wide findings, 'rep:<rep_id>' for a per-rep finding. The
natural key widens from (metric_key, window) to (metric_key, window, scope) so a
rep's declining call score and the company-wide declining call score can both
stand as separate, independently-resolvable findings. Hand-written (not
autogenerated) to avoid unrelated-index drift on this DB, matching the style of
r9c0d1e2f3a4_add_recommendations.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "v3a4b5c6d7e8"
down_revision: Union[str, None] = "u2f3a4b5c6d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "recommendations",
        sa.Column("scope", sa.String(length=64), nullable=False, server_default="global"),
    )
    op.drop_constraint(
        "uq_recommendations_metric_window", "recommendations", type_="unique"
    )
    op.create_unique_constraint(
        "uq_recommendations_metric_window_scope",
        "recommendations",
        ["metric_key", "window", "scope"],
    )


def downgrade() -> None:
    op.drop_constraint(
        "uq_recommendations_metric_window_scope", "recommendations", type_="unique"
    )
    op.create_unique_constraint(
        "uq_recommendations_metric_window", "recommendations", ["metric_key", "window"]
    )
    op.drop_column("recommendations", "scope")
