#!/usr/bin/env bash
# Provision a new Central Intelligence backend instance on a fresh droplet.
#
# One deployment per company: run this ON a brand-new Ubuntu 22.04+ droplet
# as root. It installs Docker, clones the repo at a release tag, generates
# backend/.env interactively (secrets auto-generated where possible), and
# brings the compose stack up (redis + migrate + api + worker + beat + caddy).
#
# Prerequisites (create BEFORE running — see docs/new-client-runbook.html):
#   * A dedicated Supabase project for this client (auth + app DB, pgvector).
#   * DNS control for the API domain (A record → this droplet's IP).
#   * Anthropic + Voyage API keys budgeted for this client.
#
# Usage:
#   ./provision_instance.sh <git-repo-url> <release-tag>
# Example:
#   ./provision_instance.sh https://github.com/ORG/central-intelligence.git v1.1.0
#
# Idempotent-ish: re-running updates the checkout to the tag and restarts the
# stack; it will NOT overwrite an existing backend/.env (delete it manually to
# regenerate).

set -euo pipefail

REPO_URL="${1:?usage: provision_instance.sh <git-repo-url> <release-tag>}"
RELEASE_TAG="${2:?usage: provision_instance.sh <git-repo-url> <release-tag>}"
INSTALL_DIR=/opt/central-intelligence

say()  { printf '\n\033[1;33m>>> %s\033[0m\n' "$*"; }
ask()  { local v; read -r -p "$1: " v; printf '%s' "$v"; }
asks() { local v; read -r -s -p "$1 (hidden): " v; echo >&2; printf '%s' "$v"; }

# ---------------------------------------------------------------------------
say "1/5 Installing Docker + git (skipped if present)"
# ---------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  apt-get update -y
  apt-get install -y ca-certificates curl git
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
fi
docker --version && docker compose version

# ---------------------------------------------------------------------------
say "2/5 Cloning $REPO_URL at $RELEASE_TAG into $INSTALL_DIR"
# ---------------------------------------------------------------------------
if [[ -d "$INSTALL_DIR/.git" ]]; then
  git -C "$INSTALL_DIR" fetch --tags origin
else
  git clone "$REPO_URL" "$INSTALL_DIR"
fi
git -C "$INSTALL_DIR" checkout "$RELEASE_TAG"

# ---------------------------------------------------------------------------
say "3/5 Generating backend/.env"
# ---------------------------------------------------------------------------
ENV_FILE="$INSTALL_DIR/backend/.env"
if [[ -f "$ENV_FILE" ]]; then
  say "backend/.env already exists — keeping it (delete it to regenerate)."
else
  echo "This client's own Supabase project (NEVER another client's):"
  API_DOMAIN=$(ask       "API domain (e.g. api.client.com)")
  FRONTEND_URL=$(ask     "Frontend URL for CORS (e.g. https://app.client.com)")
  DATABASE_URL=$(asks    "DATABASE_URL (postgresql+asyncpg://... session pooler)")
  SUPABASE_URL=$(ask     "SUPABASE_URL (https://<ref>.supabase.co)")
  SUPABASE_ANON_KEY=$(asks "SUPABASE_ANON_KEY")
  SUPABASE_JWT_SECRET=$(asks "SUPABASE_JWT_SECRET")
  ANTHROPIC_API_KEY=$(asks "ANTHROPIC_API_KEY")
  VOYAGE_API_KEY=$(asks  "VOYAGE_API_KEY")

  # Fernet key = url-safe base64 of 32 random bytes. Never reuse across clients.
  INTEGRATIONS_ENCRYPTION_KEY=$(openssl rand -base64 32 | tr '+/' '-_')

  umask 177
  cat > "$ENV_FILE" <<EOF
# Generated by provision_instance.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) for tag $RELEASE_TAG
# This instance serves ONE client. Never copy values from another instance.
DATABASE_URL=$DATABASE_URL
REDIS_URL=redis://redis:6379/0
DEBUG=false
MOCK_MODE=false
CORS_ORIGINS=["$FRONTEND_URL"]
API_DOMAIN=$API_DOMAIN
PUBLIC_API_BASE_URL=https://$API_DOMAIN

SUPABASE_URL=$SUPABASE_URL
SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
SUPABASE_JWT_SECRET=$SUPABASE_JWT_SECRET

ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
VOYAGE_API_KEY=$VOYAGE_API_KEY
INTEGRATIONS_ENCRYPTION_KEY=$INTEGRATIONS_ENCRYPTION_KEY

# Client source-DB sync stays OFF until their mapping is approved
# (Phase 4 onboarding). Set the URL and flip the switch then.
CLIENT_SYNC_ENABLED=false
CLIENT_DATABASE_URL=
EOF
  umask 022
  say "backend/.env written (mode 600)."
fi

# ---------------------------------------------------------------------------
say "4/5 Starting the stack (migrations run automatically via the migrate service)"
# ---------------------------------------------------------------------------
cd "$INSTALL_DIR"
docker compose up -d --build
docker compose ps

# ---------------------------------------------------------------------------
say "5/5 Done. Next steps"
# ---------------------------------------------------------------------------
cat <<'EOF'
  1. DNS: point the API domain's A record at this droplet's IP.
     Caddy provisions the HTTPS certificate automatically once DNS resolves.
  2. Verify:   curl https://<api-domain>/api/v1/health
  3. Seed the instance profile + first admin (from this directory):
       docker compose exec api python -m scripts.seed_instance \
           --profile-json /path/to/profile.json --admin-email owner@client.com
     (Create the admin user in Supabase Auth dashboard first: Authentication
      → Users → Add user, so the email exists before granting the role.)
  4. Frontend: create a separate Vercel project; set NEXT_PUBLIC_API_URL,
     NEXT_PUBLIC_WS_URL, NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY.
     Run `npm run build` locally BEFORE deploying — Vercel fails silently on lint.
  5. Full walkthrough: docs/new-client-runbook.html
EOF
